In [2]:
#Importing all the libraries and dependencies.

import pandas as pd                     
import numpy as np
%matplotlib inline
import seaborn as sns
import datetime as dt
import matplotlib.pyplot as plt
import yfinance as yf
from yahoo_fin.stock_info import get_data
import warnings
warnings.filterwarnings('ignore')

In [3]:
#List of 50 stocks/tickers

tickers = ["AAPL", "GOOGL", "AMZN", "META","TSM","MSFT", "TSLA", "NVDA", "PYPL", "INTC", "AMD", "IBM", "CSCO", "ORCL", "CRM", "ADBE", "ZM", "SQ", "DOCU", "NFLX", "SNAP", "SPOT", "DBX", "UBER", "LYFT", "WDAY", "NOW", "TEAM", "SHOP", "TWLO", "ZS", "OKTA", "MDB", "CRWD", "NET", "FSLY", "DDOG", "SNOW", "PLTR", "U", "RBLX", "AFRM", "PATH", "COUR", "COIN", "BIDU", "JD", "BABA", "TCEHY", "ZI"]

In [4]:
# S&P500 data pulled from yfinance.
data_spy = yf.download("SPY",start='2013-01-01', end='2023-05-09')
#print(data_spy)

[*********************100%***********************]  1 of 1 completed

In [5]:
#Calculate the daily return for S&P500 on adjusted closing price by using percentage change.

daily_returns_SPY500={}
daily_returns_SPY500 =data_spy['Adj Close'].pct_change().dropna()
#print(daily_returns_SPY500)
daily_returns_SPY500.name='Adj Close'

In [6]:
#Calculate Cumulative Returns bu using daily return series.
cumulative_returns=(1+daily_returns_SPY500).cumprod()-1
cumulative_returns.head()

Date
2013-01-03   -0.002259
2013-01-04    0.002123
2013-01-07   -0.000616
2013-01-08   -0.003491
2013-01-09   -0.000958
Name: Adj Close, dtype: float64

In [7]:
# Calculate Standard Deviation of S&P500.

std_of_SPY500=daily_returns_SPY500.std()

std_of_SPY500

0.010909111646796615

In [8]:
# Calculate the annualized standard deviation (252 trading days) of S&P500.

annualized_standard_deviation_SPY500 = std_of_SPY500* np.sqrt(252)
annualized_standard_deviation_SPY500

0.17317677865237285

In [9]:
# Calculate the annual average return data for the for S&P500
# Use 252 as the number of trading days in the year


trading_Days=252
annualized_average_return_SPY500=daily_returns_SPY500.mean()*trading_Days

annualized_average_return_SPY500
#annualized_average_return.sort_values(ascending=False)

0.1339524242671542

In [10]:
# Calculate the annualized Sharpe Ratios for S&P500.
risk_free_rate=0
annualized_sharpe_SPY500 = annualized_average_return_SPY500 / annualized_standard_deviation_SPY500
annualized_sharpe_SPY500

0.7735010739288792

In [11]:
#Calculate Daily return of all 50 stocks and Clean the data by dropping nan.
daily_returns={}
for ticker in tickers:
    data = yf.download(ticker,start='2013-01-01', end='2023-05-09')
    daily_return =data['Adj Close'].pct_change().dropna()
    daily_returns[ticker]=daily_return
    #print(daily_returns)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [12]:
#Create dataframe of daily return on tickers.
daily_return_df=pd.DataFrame(daily_returns)

In [13]:
#Calculate Cumulative Returns bu using daily return dataframe.
cumulative_returns=(1+daily_return_df).cumprod()-1
cumulative_returns.head()

,AAPL,GOOGL,AMZN,META,TSM,MSFT,TSLA,NVDA,PYPL,INTC,...,RBLX,AFRM,PATH,COUR,COIN,BIDU,JD,BABA,TCEHY,ZI
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-03,-0.012623,0.000581,0.004547,-0.008214,-0.000553,-0.013396,-0.016685,0.000786,NaN,-0.002806,...,NaN,NaN,NaN,NaN,NaN,0.008260,NaN,NaN,-0.008929,NaN
2013-01-04,-0.040126,0.020353,0.007151,0.027143,-0.007735,-0.031861,-0.027149,0.033805,NaN,-0.010290,...,NaN,NaN,NaN,NaN,NaN,0.005090,NaN,NaN,-0.003869,NaN
2013-01-07,-0.045772,0.015900,0.043333,0.050714,-0.022100,-0.033671,-0.028846,0.003931,NaN,-0.006080,...,NaN,NaN,NaN,NaN,NaN,-0.017576,NaN,NaN,-0.017857,NaN
2013-01-08,-0.043204,0.013896,0.035249,0.037857,-0.030939,-0.038740,-0.047511,-0.018082,NaN,-0.013564,...,NaN,NaN,NaN,NaN,NaN,-0.029101,NaN,NaN,-0.022321,NaN
2013-01-09,-0.058157,0.020560,0.035133,0.092500,-0.030939,-0.033309,-0.048642,-0.040094,NaN,0.003275,...,NaN,NaN,NaN,NaN,NaN,0.002113,NaN,NaN,-0.027083,NaN

In [14]:
# Calculate and sort the standard deviation for all 50 stocks.
# Review the standard deviations sorted largest to smallest.

std_of_ticker=daily_return_df.std()
std_of_ticker_sorted=std_of_ticker.sort_values(ascending=False)
std_of_ticker_sorted

AFRM     0.071972
COIN     0.059883
FSLY     0.055725
RBLX     0.055713
U        0.052964
SNAP     0.048395
NET      0.048316
PLTR     0.046741
LYFT     0.045779
PATH     0.044923
SNOW     0.043304
MDB      0.042230
DDOG     0.041319
ZM       0.041210
TWLO     0.040518
ZI       0.039929
SHOP     0.039658
ZS       0.039451
CRWD     0.039433
DOCU     0.039328
COUR     0.038950
SQ       0.037528
UBER     0.037221
AMD      0.036650
TSLA     0.036194
OKTA     0.034938
TEAM     0.032761
SPOT     0.031409
JD       0.030422
NFLX     0.029889
NVDA     0.028029
BIDU     0.027904
BABA     0.026639
DBX      0.026630
NOW      0.025919
WDAY     0.024795
META     0.024487
PYPL     0.024257
TCEHY    0.024049
CRM      0.021969
AMZN     0.020668
ADBE     0.019916
INTC     0.019574
TSM      0.018638
AAPL     0.018215
GOOGL    0.017258
MSFT     0.017110
ORCL     0.016014
CSCO     0.015898
IBM      0.014670
dtype: float64

In [15]:
# Calculate and sort the annualized standard deviation (252 trading days) of all 50 stocks.
# Review the annualized std dev. sorted from highest to lowest.
annualized_standard_deviation = std_of_ticker* np.sqrt(252)
annualized_standard_deviation.sort_values(ascending=False)
annualized_standard_deviation.sort_values(ascending=False).head()

AFRM    1.142517
COIN    0.950608
FSLY    0.884612
RBLX    0.884421
U       0.840778
dtype: float64

In [16]:
# Calculate the annual average return data for the for 50 tickers.
# Use 252 as the number of trading days in the year
# Review the annual average returns sorted from highest to lowest.

trading_Days=252
annualized_average_return=daily_return_df.mean()*trading_Days
annualized_average_return.sort_values(ascending=False)
annualized_average_return.sort_values(ascending=False).head()

SHOP    0.646043
MDB     0.587277
TSLA    0.578524
NVDA    0.542140
NET     0.538213
dtype: float64

In [17]:
# Calculate the annualized Sharpe Ratios for each of the 50 Stocks.
# Review the Sharpe ratios sorted highest to lowest

risk_free_rate=0
annualized_sharpe = annualized_average_return / annualized_standard_deviation
annualized_sharpe_sorted=annualized_sharpe.sort_values(ascending=False)
annualized_sharpe_sorted
type(annualized_sharpe_sorted)

pandas.core.series.Series

In [18]:
# Optimization 

rank_risk_Return={}

# Top 10%
for i in range(1, 16):
    rank_risk_Return[i] = 'High Volatility'

# Middle 20%
for i in range(16, 32):
    rank_risk_Return[i] = 'Medium Volatility'

# Bottom 20%
for i in range(32, 51):
    rank_risk_Return[i] = 'Low Volatility'
    

#print(rank_risk_Return)

# add rank number to the index of std_devs series
ranked_std_dev = std_of_ticker_sorted.rank(ascending=False) 
#print(ranked_std_dev)

# create a DataFrame from the ranked_std_dev series
std_dev_df = pd.DataFrame(ranked_std_dev, columns=['Rank'])
#print(std_dev_df)
# add the corresponding ticker symbols to the DataFrame
std_dev_df['Ticker'] = std_of_ticker_sorted.index
#print(std_dev_df)
# set the ticker column as the index
std_dev_df.set_index('Ticker', inplace=True)

# create a new column in the std_devs DataFrame to store the group
std_dev_df['Group'] = ranked_std_dev.apply(lambda x: rank_risk_Return.get(x, 'Unknown'))

# sort the std_devs_df DataFrame based on rank
#std_dev_df.sort_values(by=['Rank'], inplace=True)


#std_dev_df

In [19]:
# create a dictionary to store the ranked tickers
ranked_tickers_std = {
    "Group 1": list(ranked_std_dev[ranked_std_dev <= 15].index),
    "Group 2": list(ranked_std_dev[(ranked_std_dev > 15) & (ranked_std_dev <= 31)].index),
    "Group 3": list(ranked_std_dev[ranked_std_dev > 31].index),
}

print(ranked_tickers_std)

# This will output a dictionary with three keys, "Group 1", "Group 2", and "Group 3", 
# with the respective tickers for each group. 
# The stocks are grouped based on their rank, 
# where Group 1 has the highest volatility, 
# Group 2 has medium volatility, 
# and Group 3 has the lowest volatility.

{'Group 1': ['AFRM', 'COIN', 'FSLY', 'RBLX', 'U', 'SNAP', 'NET', 'PLTR', 'LYFT', 'PATH', 'SNOW', 'MDB', 'DDOG', 'ZM', 'TWLO'], 'Group 2': ['ZI', 'SHOP', 'ZS', 'CRWD', 'DOCU', 'COUR', 'SQ', 'UBER', 'AMD', 'TSLA', 'OKTA', 'TEAM', 'SPOT', 'JD', 'NFLX', 'NVDA'], 'Group 3': ['BIDU', 'BABA', 'DBX', 'NOW', 'WDAY', 'META', 'PYPL', 'TCEHY', 'CRM', 'AMZN', 'ADBE', 'INTC', 'TSM', 'AAPL', 'GOOGL', 'MSFT', 'ORCL', 'CSCO', 'IBM']}

In [20]:
Sharpe_rank_risk_Return={}

# Top 10%
for i in range(1, 16):
    Sharpe_rank_risk_Return[i] = 'High Return'

# Middle 20%
for i in range(16, 32):
    Sharpe_rank_risk_Return[i] = 'Medium Return'

# Bottom 20%
for i in range(32, 51):
    Sharpe_rank_risk_Return[i] = 'Low Return'
    

#print(rank_risk_Return)

# add rank number to the index of sharpe_ratio series
ranked_sharpe_ratio = annualized_sharpe_sorted.rank(ascending=False) 
#print(ranked_std_dev)

# create a DataFrame from the ranked_sharpe_ratio series
sharpe_ratio_df = pd.DataFrame(ranked_sharpe_ratio, columns=['Rank'])
#print(sharpe_ratio_df)
# add the corresponding ticker symbols to the DataFrame
sharpe_ratio_df['Ticker'] = annualized_sharpe_sorted.index
#print(std_dev_df)
# set the ticker column as the index
sharpe_ratio_df.set_index('Ticker', inplace=True)

# create a new column in the sharpe ratio DataFrame to store the group
sharpe_ratio_df['Group'] = ranked_sharpe_ratio.apply(lambda x: Sharpe_rank_risk_Return.get(x, 'Unknown'))

# sort the sharpe_ratio_df DataFrame based on rank
sharpe_ratio_df.sort_values(by=['Rank'], inplace=True)

#Print the top 10 High return stock based on sharpe ratio.
sharpe_ratio_df

        Rank          Group
Ticker
NVDA     1.0    High Return
MSFT     2.0    High Return
SHOP     3.0    High Return
TSLA     4.0    High Return
AAPL     5.0    High Return
NFLX     6.0    High Return
AMD      7.0    High Return
MDB      8.0    High Return
ADBE     9.0    High Return
NOW     10.0    High Return
AMZN    11.0    High Return
GOOGL   12.0    High Return
TSM     13.0    High Return
TEAM    14.0    High Return
META    15.0    High Return
NET     16.0  Medium Return
TCEHY   17.0  Medium Return
SQ      18.0  Medium Return
DDOG    19.0  Medium Return
OKTA    20.0  Medium Return
ZS      21.0  Medium Return
CRWD    22.0  Medium Return
CRM     23.0  Medium Return
ORCL    24.0  Medium Return
CSCO    25.0  Medium Return
WDAY    26.0  Medium Return
TWLO    27.0  Medium Return
PYPL    28.0  Medium Return
DOCU    29.0  Medium Return
JD      30.0  Medium Return
INTC    31.0  Medium Return
ZM      32.0     Low Return
BIDU    33.0     Low Return
UBER    34.0     Low Return
FSLY    35.0     Low Return
PLTR    36.0     Low Return
SPOT    37.0     Low Return
BABA    38.0     Low Return
SNAP    39.0     Low Return
IBM     40.0     Low Return
DBX     41.0     Low Return
RBLX    42.0     Low Return
SNOW    43.0     Low Return
ZI      44.0     Low Return
U       45.0     Low Return
AFRM    46.0     Low Return
LYFT    47.0     Low Return
COIN    48.0     Low Return
COUR    49.0     Low Return
PATH    50.0     Low Return

In [21]:
# create a dictionary to store the ranked tickers
ranked_tickers_sharpe = {
    "Group 1": list(ranked_sharpe_ratio[ranked_sharpe_ratio <= 15].index),
    "Group 2": list(ranked_sharpe_ratio[(ranked_sharpe_ratio > 15) & (ranked_sharpe_ratio <= 31)].index),
    "Group 3": list(ranked_sharpe_ratio[ranked_sharpe_ratio > 31].index),
}

print(ranked_tickers_sharpe)

# This will output a dictionary with three keys, "Group 1", "Group 2", and "Group 3", 
# with the respective tickers for each group. 
# The stocks are grouped based on their rank, 
# where Group 1 has the highest return, 
# Group 2 has medium return, 
# and Group 3 has the lowest return.

{'Group 1': ['NVDA', 'MSFT', 'SHOP', 'TSLA', 'AAPL', 'NFLX', 'AMD', 'MDB', 'ADBE', 'NOW', 'AMZN', 'GOOGL', 'TSM', 'TEAM', 'META'], 'Group 2': ['NET', 'TCEHY', 'SQ', 'DDOG', 'OKTA', 'ZS', 'CRWD', 'CRM', 'ORCL', 'CSCO', 'WDAY', 'TWLO', 'PYPL', 'DOCU', 'JD', 'INTC'], 'Group 3': ['ZM', 'BIDU', 'UBER', 'FSLY', 'PLTR', 'SPOT', 'BABA', 'SNAP', 'IBM', 'DBX', 'RBLX', 'SNOW', 'ZI', 'U', 'AFRM', 'LYFT', 'COIN', 'COUR', 'PATH']}

In [22]:
# Calculation Covariance of all 50 stocks to compare it with variance of s&p500.

covariance_50stocks={}
for ticker in tickers:
    covariance_each_stock_with_SPY500= daily_return_df[ticker].cov(daily_returns_SPY500)
    covariance_50stocks[ticker]=covariance_each_stock_with_SPY500

print(covariance_50stocks)

{'AAPL': 0.00014125105707383305, 'GOOGL': 0.0001370720519982515, 'AMZN': 0.0001374755245325883, 'META': 0.00015144597002198596, 'TSM': 0.00012239248727345716, 'MSFT': 0.00014347142726480624, 'TSLA': 0.00017279702080407342, 'NVDA': 0.0001956528489518255, 'PYPL': 0.00018869404140114796, 'INTC': 0.0001423202323741791, 'AMD': 0.00018998579053149713, 'IBM': 0.00010144561210498256, 'CSCO': 0.00011951413784063307, 'ORCL': 0.00011360927566240216, 'CRM': 0.00015198360748652559, 'ADBE': 0.00015228200077514533, 'ZM': 0.00013147130048600427, 'SQ': 0.00026736663834348067, 'DOCU': 0.00023872075422336168, 'NFLX': 0.00014132211323261335, 'SNAP': 0.00022386560038610936, 'SPOT': 0.00020070699922044208, 'DBX': 0.00018264939154549362, 'UBER': 0.00027216168484990664, 'LYFT': 0.000293781428587927, 'WDAY': 0.00015226568573863252, 'NOW': 0.00016578801024201255, 'TEAM': 0.0001725666282441929, 'SHOP': 0.0002254321106698544, 'TWLO': 0.00021269757912738873, 'ZS': 0.0002216479222913352, 'OKTA': 0.00019842557954893042, 'MDB': 0.0002607211545939557, 'CRWD': 0.00024086964283278166, 'NET': 0.00030906222506286307, 'FSLY': 0.00032180535296252486, 'DDOG': 0.00028157760151227844, 'SNOW': 0.0002608457534691708, 'PLTR': 0.000240726438761397, 'U': 0.0003442124622758468, 'RBLX': 0.00030441807311632103, 'AFRM': 0.00048818848962269636, 'PATH': 0.00030322405855541664, 'COUR': 0.0002164271618045423, 'COIN': 0.00041127872738629595, 'BIDU': 0.00013471983990108276, 'JD': 0.00014657787168121677, 'BABA': 0.00013247273491119943, 'TCEHY': 0.00011329341192130455, 'ZI': 0.00023820392284260746}

In [23]:
#Create DataFrame for all Tickers and covariance.
#pd.DataFrame(covariance_50stocks)
df_final = pd.DataFrame(covariance_50stocks.items())
df_final.columns = ['Ticker','Covariance']
df_final.head()

  Ticker  Covariance
0   AAPL    0.000141
1  GOOGL    0.000137
2   AMZN    0.000137
3   META    0.000151
4    TSM    0.000122

In [24]:
#Calculate the variance of S&P500.

sp500_Var=daily_returns_SPY500.var()
sp500_Var

0.00011900871692227358

In [25]:
#Calculate Correlation between each ticker with s&p500.

correlation_50stocks={}

for ticker in tickers:
    correlation_each_stock_with_SPY500= daily_return_df[ticker].corr(daily_returns_SPY500)
    correlation_50stocks[ticker]=correlation_each_stock_with_SPY500

correlation_50stocks

{'AAPL': 0.7106864009994154,
 'GOOGL': 0.7279443581740123,
 'AMZN': 0.609620123039598,
 'META': 0.5668154949818704,
 'TSM': 0.6018379882249453,
 'MSFT': 0.7684948151047014,
 'TSLA': 0.43754352415394077,
 'NVDA': 0.6397466175548516,
 'PYPL': 0.6548653307582151,
 'INTC': 0.6663678819014438,
 'AMD': 0.4750870555221743,
 'IBM': 0.6337508513997392,
 'CSCO': 0.688954444124412,
 'ORCL': 0.6501970913818564,
 'CRM': 0.6340407297673545,
 'ADBE': 0.7007838024715785,
 'ZM': 0.22393622621773313,
 'SQ': 0.5997630576430135,
 'DOCU': 0.45138528521791527,
 'NFLX': 0.4333343993100098,
 'SNAP': 0.3691704246640547,
 'SPOT': 0.47688715254914943,
 'DBX': 0.5110269293740666,
 'UBER': 0.5102080090532457,
 'LYFT': 0.4532731973695688,
 'WDAY': 0.5628219157649398,
 'NOW': 0.5862154046521668,
 'TEAM': 0.4427117837254187,
 'SHOP': 0.48105418006036615,
 'TWLO': 0.4351635473781964,
 'ZS': 0.4182249886163824,
 'OKTA': 0.44981956964050124,
 'MDB': 0.4694242468197417,
 'CRWD': 0.42380077411043116,
 'NET': 0.43504713737387546,
 'FSLY': 0.4028114803937834,
 'DDOG': 0.46248192957635675,
 'SNOW': 0.5102226336150603,
 'PLTR': 0.43678198778672916,
 'U': 0.5503427937448062,
 'RBLX': 0.4526968735630385,
 'AFRM': 0.5654350526874656,
 'PATH': 0.5493989548469402,
 'COUR': 0.4563369082818637,
 'COIN': 0.5606825068449713,
 'BIDU': 0.44247937729117126,
 'JD': 0.4225296185691905,
 'BABA': 0.4294314900037976,
 'TCEHY': 0.4317473824407273,
 'ZI': 0.5003242734617949}

In [26]:
#Calculate the beta based on the covariance of stocks compared to the market (S&P 500)
#Assigning the calculated Correlation values to dataframe.

df_final['Beta'] = df_final['Covariance']/sp500_Var
df_final['Correlation']=correlation_50stocks.values()

df_final.head()

  Ticker  Covariance      Beta  Correlation
0   AAPL    0.000141  1.186897     0.710686
1  GOOGL    0.000137  1.151782     0.727944
2   AMZN    0.000137  1.155172     0.609620
3   META    0.000151  1.272562     0.566815
4    TSM    0.000122  1.028433     0.601838

In [27]:
# Optimization on the basis of beta.
#Sorting based on beta in descending order.
df_final_sorted_by_beta=df_final.sort_values(by=['Beta'],ascending=False)

# ranking them in descending order of beta.
df_final_sorted_by_beta['Rank'] = df_final_sorted_by_beta['Beta'].rank(ascending=False) 
print(df_final_sorted_by_beta.head())

   Ticker  Covariance      Beta  Correlation  Rank
41   AFRM    0.000488  4.102124     0.565435   1.0
44   COIN    0.000411  3.455871     0.560683   2.0
39      U    0.000344  2.892330     0.550343   3.0
35   FSLY    0.000322  2.704049     0.402811   4.0
34    NET    0.000309  2.596971     0.435047   5.0

In [28]:
#Grouping them based on rank.
#Adding new column "Sensitivity" based on criteria-
#Rank (1 to 15)= 'High Sensitivity'
#Rank (16 to 31)= 'Medium Sensitivity'
#Rank (32 to 50)= 'low Sensitivity'
df_final_sorted_by_beta['sensitivity'] = ''
df_final_sorted_by_beta.loc[df_final_sorted_by_beta['Rank']<16,'sensitivity'] = 'High Sensitivity'
df_final_sorted_by_beta.loc[(df_final_sorted_by_beta['Rank']>=16)&(df_final_sorted_by_beta['Rank']<32),'sensitivity'] = 'Medium Sensitivity'
df_final_sorted_by_beta.loc[df_final_sorted_by_beta['Rank']>=32,'sensitivity']='Low Sensitivity'

In [52]:
#Sorted the dataframe and rank them by beta.

df_final_sorted_by_beta.tail(20)

   Ticker  Covariance      Beta  Correlation  Rank         sensitivity
26    NOW    0.000166  1.393075     0.586215  31.0  Medium Sensitivity
15   ADBE    0.000152  1.279587     0.700784  32.0     Low Sensitivity
25   WDAY    0.000152  1.279450     0.562822  33.0     Low Sensitivity
14    CRM    0.000152  1.277080     0.634041  34.0     Low Sensitivity
3    META    0.000151  1.272562     0.566815  35.0     Low Sensitivity
46     JD    0.000147  1.231657     0.422530  36.0     Low Sensitivity
5    MSFT    0.000143  1.205554     0.768495  37.0     Low Sensitivity
9    INTC    0.000142  1.195881     0.666368  38.0     Low Sensitivity
19   NFLX    0.000141  1.187494     0.433334  39.0     Low Sensitivity
0    AAPL    0.000141  1.186897     0.710686  40.0     Low Sensitivity
2    AMZN    0.000137  1.155172     0.609620  41.0     Low Sensitivity
1   GOOGL    0.000137  1.151782     0.727944  42.0     Low Sensitivity
45   BIDU    0.000135  1.132017     0.442479  43.0     Low Sensitivity
47   BABA    0.000132  1.113135     0.429431  44.0     Low Sensitivity
16     ZM    0.000131  1.104720     0.223936  45.0     Low Sensitivity
4     TSM    0.000122  1.028433     0.601838  46.0     Low Sensitivity
12   CSCO    0.000120  1.004247     0.688954  47.0     Low Sensitivity
13   ORCL    0.000114  0.954630     0.650197  48.0     Low Sensitivity
48  TCEHY    0.000113  0.951976     0.431747  49.0     Low Sensitivity
11    IBM    0.000101  0.852422     0.633751  50.0     Low Sensitivity

In [30]:
# Optimization on the basis of Correlation.
#Sorting based on Correlation in descending order.
df_final_sorted_by_Correlation=df_final.sort_values(by=['Correlation'],ascending=False)

# ranking them in descending order of Correlation.
df_final_sorted_by_Correlation['Rank'] = df_final_sorted_by_Correlation['Correlation'].rank(ascending=False) 
print(df_final_sorted_by_Correlation.head(10))

   Ticker  Covariance      Beta  Correlation  Rank
5    MSFT    0.000143  1.205554     0.768495   1.0
1   GOOGL    0.000137  1.151782     0.727944   2.0
0    AAPL    0.000141  1.186897     0.710686   3.0
15   ADBE    0.000152  1.279587     0.700784   4.0
12   CSCO    0.000120  1.004247     0.688954   5.0
9    INTC    0.000142  1.195881     0.666368   6.0
8    PYPL    0.000189  1.585548     0.654865   7.0
13   ORCL    0.000114  0.954630     0.650197   8.0
7    NVDA    0.000196  1.644021     0.639747   9.0
14    CRM    0.000152  1.277080     0.634041  10.0

In [31]:
#Grouping them based on rank.
#Adding new column "Correlation Type" based on criteria-
#Rank (1 to 15)= 'Highly Correlated'
#Rank (16 to 31)= 'Moderatly Correlated'
#Rank (32 to 50)= 'less Correlated'


df_final_sorted_by_Correlation['Correlation Type'] = ''
df_final_sorted_by_Correlation.loc[df_final_sorted_by_Correlation['Rank']<16,'Correlation Type'] = 'Highly Correlated'
df_final_sorted_by_Correlation.loc[(df_final_sorted_by_Correlation['Rank']>=16)&(df_final_sorted_by_Correlation['Rank']<32),'Correlation Type'] = 'Moderatly Correlated'
df_final_sorted_by_Correlation.loc[df_final_sorted_by_Correlation['Rank']>=32,'Correlation Type']='Less Correlated'
df_final_sorted_by_Correlation

   Ticker  Covariance      Beta  Correlation  Rank      Correlation Type
5    MSFT    0.000143  1.205554     0.768495   1.0     Highly Correlated
1   GOOGL    0.000137  1.151782     0.727944   2.0     Highly Correlated
0    AAPL    0.000141  1.186897     0.710686   3.0     Highly Correlated
15   ADBE    0.000152  1.279587     0.700784   4.0     Highly Correlated
12   CSCO    0.000120  1.004247     0.688954   5.0     Highly Correlated
9    INTC    0.000142  1.195881     0.666368   6.0     Highly Correlated
8    PYPL    0.000189  1.585548     0.654865   7.0     Highly Correlated
13   ORCL    0.000114  0.954630     0.650197   8.0     Highly Correlated
7    NVDA    0.000196  1.644021     0.639747   9.0     Highly Correlated
14    CRM    0.000152  1.277080     0.634041  10.0     Highly Correlated
11    IBM    0.000101  0.852422     0.633751  11.0     Highly Correlated
2    AMZN    0.000137  1.155172     0.609620  12.0     Highly Correlated
4     TSM    0.000122  1.028433     0.601838  13.0     Highly Correlated
17     SQ    0.000267  2.246614     0.599763  14.0     Highly Correlated
26    NOW    0.000166  1.393075     0.586215  15.0     Highly Correlated
3    META    0.000151  1.272562     0.566815  16.0  Moderatly Correlated
41   AFRM    0.000488  4.102124     0.565435  17.0  Moderatly Correlated
25   WDAY    0.000152  1.279450     0.562822  18.0  Moderatly Correlated
44   COIN    0.000411  3.455871     0.560683  19.0  Moderatly Correlated
39      U    0.000344  2.892330     0.550343  20.0  Moderatly Correlated
42   PATH    0.000303  2.547915     0.549399  21.0  Moderatly Correlated
22    DBX    0.000183  1.534756     0.511027  22.0  Moderatly Correlated
37   SNOW    0.000261  2.191821     0.510223  23.0  Moderatly Correlated
23   UBER    0.000272  2.286905     0.510208  24.0  Moderatly Correlated
49     ZI    0.000238  2.001567     0.500324  25.0  Moderatly Correlated
28   SHOP    0.000225  1.894249     0.481054  26.0  Moderatly Correlated
21   SPOT    0.000201  1.686490     0.476887  27.0  Moderatly Correlated
10    AMD    0.000190  1.596402     0.475087  28.0  Moderatly Correlated
32    MDB    0.000261  2.190774     0.469424  29.0  Moderatly Correlated
36   DDOG    0.000282  2.366025     0.462482  30.0  Moderatly Correlated
43   COUR    0.000216  1.818582     0.456337  31.0  Moderatly Correlated
24   LYFT    0.000294  2.468571     0.453273  32.0       Less Correlated
40   RBLX    0.000304  2.557948     0.452697  33.0       Less Correlated
18   DOCU    0.000239  2.005910     0.451385  34.0       Less Correlated
31   OKTA    0.000198  1.667320     0.449820  35.0       Less Correlated
27   TEAM    0.000173  1.450034     0.442712  36.0       Less Correlated
45   BIDU    0.000135  1.132017     0.442479  37.0       Less Correlated
6    TSLA    0.000173  1.451969     0.437544  38.0       Less Correlated
38   PLTR    0.000241  2.022763     0.436782  39.0       Less Correlated
29   TWLO    0.000213  1.787244     0.435164  40.0       Less Correlated
34    NET    0.000309  2.596971     0.435047  41.0       Less Correlated
19   NFLX    0.000141  1.187494     0.433334  42.0       Less Correlated
48  TCEHY    0.000113  0.951976     0.431747  43.0       Less Correlated
47   BABA    0.000132  1.113135     0.429431  44.0       Less Correlated
33   CRWD    0.000241  2.023966     0.423801  45.0       Less Correlated
46     JD    0.000147  1.231657     0.422530  46.0       Less Correlated
30     ZS    0.000222  1.862451     0.418225  47.0       Less Correlated
35   FSLY    0.000322  2.704049     0.402811  48.0       Less Correlated
20   SNAP    0.000224  1.881086     0.369170  49.0       Less Correlated
16     ZM    0.000131  1.104720     0.223936  50.0       Less Correlated